apps/front/forms.py
__author__ = 'yuchen'
__date__ = '2018/8/27 17:39'

from apps.common.forms import BaseForm
from wtforms import StringField,IntegerField
from wtforms.validators import Regexp, Length, EqualTo, ValidationError,InputRequired,DataRequired
from utils import landicache
from .models import FrontUser
from config import FRONT_USER_ID





class IForgetForm(BaseForm):
    telephone = StringField(validators=[Regexp(r'1[35678]\d{9}', message='手机号码格式错误'),DataRequired(message='请输入空缺手机号')])
    sms_captcha = StringField(validators=[Regexp(r'\w{4}', message='短信验证码错误'),DataRequired(message='请输入短信验证码')])
    password1 = StringField(validators=[Regexp(r'^(?![0-9]+$)(?![a-zA-Z]+$)[0-9A-Za-z]{6,16}$',
                                               message='密码需要6位以上数字和字母的组合'),DataRequired(message='请输入空缺密码内容')])
    password2 = StringField(validators=[EqualTo('password1', message='两次密码不一致'),DataRequired(message='请重复输入密码')])
    graph_captcha = StringField(validators=[Regexp(r'\w{4}', message='图形验证码错误'),DataRequired(message='请输入图形验证码')])



    def validate_telephone(self, field):
        user = FrontUser.query.filter_by(telephone=field.data).first()
        if not user:
            raise ValidationError('该手机号未被注册')


    def validate_sms_captcha(self, field):
        telephone = self.telephone.data
        sms_captcha = field.data

        sms_captcha_restore = landicache.get(telephone)
        print('用户输入的短信验证码：{}'.format(sms_captcha))
        print('服务器存储的短信验证码：{}'.format(sms_captcha_restore))
        if not sms_captcha_restore or sms_captcha_restore != sms_captcha.lower():
            raise ValidationError(message='短信验证码错误')

    def validate_graph_captcha(self, field):
        graph_captcha = field.data
        print('用户输入的图形验证码是', graph_captcha)
        # 因为图形验证码存储的key和值都是一样的，所以我们只要判断key是否存在就行
        if not landicache.get(graph_captcha.lower()):
            raise ValidationError(message='图形验证码错误')


class SignUpForm(BaseForm):
    telephone = StringField(validators=[Regexp(r'1[35678]\d{9}',message='手机号码格式错误')])
    sms_captcha = StringField(validators=[Regexp(r'\w{4}', message='短信验证码错误')])
    username = StringField(validators=[Length(2,20, message='用户名格式错误')])
    password1 = StringField(validators=[Regexp(r'^(?![0-9]+$)(?![a-zA-Z]+$)[0-9A-Za-z]{6,16}$',
                                               message='密码需要6位以上数字和字母的组合')])
    password2 = StringField(validators=[EqualTo('password1', message='两次密码不一致')])
    graph_captcha = StringField(validators=[Regexp(r'\w{4}', message='图形验证码错误')])

    def validate_telephone(self, field):
        user = FrontUser.query.filter_by(telephone=field.data).first()
        if user:
            raise ValidationError('该手机号已被注册')

    def validate_sms_captcha(self, field):
        telephone = self.telephone.data
        sms_captcha = field.data

        sms_captcha_restore = landicache.get(telephone)
        print('用户输入的短信验证码：{}'.format(sms_captcha))
        print( '服务器存储的短信验证码：{}'.format(sms_captcha_restore))
        if not sms_captcha_restore or sms_captcha_restore != sms_captcha.lower():
            raise ValidationError(message='短信验证码错误')

    def validate_graph_captcha(self, field):
        graph_captcha = field.data
        print('用户输入的图形验证码是',graph_captcha)
        #因为图形验证码存储的key和值都是一样的，所以我们只要判断key是否存在就行
        if not landicache.get(graph_captcha.lower()):
            raise ValidationError(message='图形验证码错误')

class LoginForm(BaseForm):
    telephone = StringField(validators=[Regexp(r'1[35678]\d{9}', message='手机号码格式错误')])
    password=StringField(validators=[Length(6,20,message='请输入正确格式的密码')])
    remember=IntegerField()


class AddPostForm(BaseForm):
    title=StringField(validators=[InputRequired(message='请输入标题')])
    content=StringField(validators=[InputRequired(message='请输入内容')])
    board_id=IntegerField(validators=[InputRequired(message='请选择版块')])

class AddCommentForm(BaseForm):
    content=StringField(validators=[InputRequired(message='请输入评论内容')])
    post_id=IntegerField(validators=[InputRequired(message='请输入评论内容')])

apps/common/views.py
__author__ = 'yuchen'
__date__ = '2018/8/27 17:38'

from flask import Blueprint, make_response,request
from utils.captcha import Captcha
from io import BytesIO
from yunpian_python_sdk.model import constant as YC
from yunpian_python_sdk.ypclient import YunpianClient
from config import DevConfig
from utils import resful
import string
import random
from .forms import SmsCaptchaForm
from utils import landicache

bp=Blueprint('common',__name__,url_prefix='/c')



@bp.route('/')
def index():
    return 'common index'




@bp.route('/captcha/')
def graph_captcha():
    #调用得到验证码
    text,image=Captcha.gene_graph_captcha()
    #bytesIO二进制流
    out=BytesIO()
    image.save(out,'png')
    out.seek(0)
    resp=make_response(out.read())
    resp.content_type='image/png'
    print('前端生成的图形验证码是',text.lower())
    landicache.set(text.lower(),text.lower())
    print('后端生成的图形验证码',landicache.get(text.lower()))
    return resp

def get_back_random_cptcha():
    source = list(string.ascii_letters)
    source.extend(map(lambda x: str(x), range(0, 10)))

    # 还有一种写法,但是太low了
    # source.extend(['0','1','2','3','4','5','6','7','8','9','10'])
    random_code_captcha = random.sample(source, 4)
    captcha_code = ''.join(random_code_captcha)
    return captcha_code

@bp.route('/sms_captcha/',methods=['POST'])
def sms_captcha():
    form=SmsCaptchaForm(request.form)
    if form.validate():
        telephone=form.telephone.data
        captcha=get_back_random_cptcha()
        print('电话号码是',telephone)
        print('发送给用户的短信验证码是',captcha)
        #在memcache里存telephone和验证码
        landicache.set(telephone,captcha.lower())
        # message='【雨晨论坛】您的验证码是{}。如非本人操作，请忽略本短信'.format(captcha)
        # clnt = YunpianClient(DevConfig.YUNPIAN_CODE)
        # param = {YC.MOBILE: telephone, YC.TEXT: message}
        # if clnt.sms().single_send(param):
        #     #在memcache里存telephone和验证码
        #     landicache.set(telephone,captcha.lower())
        #     return resful.success('短信验证码发送成功')
        # else:
        #     return resful.params_error(message='请传入手机号码')
        return resful.success('短K信验证码发送成功')
    else:
        return resful.params_error(message='参数错误')
        # return resful.success('曾博的成功')

apps/front/__init__.py
__author__ = 'yuchen'
__date__ = '2018/8/27 17:37'

from .views import bp
from . import hooks

apps/front/views.py
__author__ = 'yuchen'
__date__ = '2018/8/27 17:38'

from flask import (
    Blueprint,
    views,
    render_template,
    make_response,
    request,
    session,
    redirect,
    url_for,
    g,
    abort
)
from config import FRONT_USER_ID
from io import BytesIO
from utils.captcha import Captcha
from .forms import SignUpForm,LoginForm,AddPostForm,AddCommentForm,IForgetForm
from .models import FrontUser
from exts import db
from utils import resful,safeutils
from apps.front.models import BannerModel,BoardModel,PostModel,CommentModel,HighLight
from .decorators import login_requried
from flask_paginate import Pagination,get_page_parameter
from config import DevConfig



from sqlalchemy import func,or_

bp=Blueprint('front',__name__)



@bp.route('/')
def index():
    board_id=request.args.get('bd',type=int,default=None)
    page = request.args.get(get_page_parameter(), type=int, default=1)
    sort = request.args.get('st', type=int, default=1)

    banners = BannerModel.query.order_by(BannerModel.priority.desc()).limit(4)
    boards = BoardModel.query.all()

    start = (page-1)*DevConfig.PER_PAGE
    end=start+DevConfig.PER_PAGE
    posts=None
    total=0
    query_obj = None

    if sort == 1:
        query_obj = PostModel.query.order_by(PostModel.create_time.desc())
    elif sort == 2:
        query_obj = db.session.query(PostModel).outerjoin(HighLight).order_by(HighLight.create_time.desc(),
                                                                              PostModel.create_time.desc())
    elif sort == 3:
        query_obj = PostModel.query.order_by(PostModel.reading_count.desc())
    elif sort == 4:
        query_obj = db.session.query(PostModel).outerjoin(CommentModel).group_by(PostModel.id).order_by(
            func.count(CommentModel.id).desc(), PostModel.create_time.desc())


    if board_id:
        query_board=query_obj.filter(PostModel.board_id==board_id).order_by(PostModel.create_time.desc())
        posts=query_board.slice(start,end)
        total=query_board.count()
    else:
        posts=query_obj.slice(start,end)
        total=query_obj.count()
    pagination = Pagination(bs_version=3,page=page, total=total,outer_window=0,inner_window=3)
    context = {
        'banners': banners,
        'boards': boards,
        'posts': posts,
        'pagination':pagination,
        'current_board':board_id,
        'current_sort':sort
    }
    return render_template('front/front_index.html', **context)



@bp.route('/captcha/')
def graph_captcha():
    #调用得到验证码
    text,image=Captcha.gene_graph_captcha()
    #bytesIO二进制流
    out=BytesIO()
    image.save(out,'png')
    out.seek(0)
    resp=make_response(out.read())
    resp.content_type='image/png'
    return resp


@bp.route('/login/',methods=['POST','GET'])
def login_in():
    if request.method =='GET':
        if session.get(FRONT_USER_ID):
            return redirect(url_for('front.index'))
        else:
            return_to=request.referrer
            if return_to and return_to!=request.url \
                    and return_to != url_for('front.signup') and safeutils.is_safe_url(return_to):
                return render_template('front/front_login.html',return_to=return_to)
            return render_template('front/front_login.html')
    else:
        form=LoginForm(request.form)
        # print(form.data)
        if form.validate():
            telephone=form.telephone.data
            password=form.password.data
            remember=form.remember.data
            user=FrontUser.query.filter_by(telephone=telephone).first()
            if user and user.check_password(password):
                session[FRONT_USER_ID]=user.id
                if remember:
                    session.permanent = True
                return resful.success()
            else:
                return resful.params_error('手机号或密码错误')
        else:
            return resful.params_error(form.get_error())

@bp.route('/logout/')
def log_out():
    del session[FRONT_USER_ID]
    return redirect(url_for('front.index'))

    

class SignUpViews(views.MethodView):
    def get(self):
        # 获取上一个页面的url
        return_to = request.referrer
        # referrer不一定会存在，比如直接访问的登录页面
        # 并且它不等于登录页面的url
        # 并且这个referre是个安全的url,防止恶意者去伪造它，被跳转到其它恶意的网站
        if return_to and return_to != request.url and safeutils.is_safe_url(return_to):
            # 把这个url传入到模板中
            return render_template('front/front_signup.html', return_to=return_to)
        return render_template('front/front_signup.html')

    def post(self):
        form=SignUpForm(request.form)
        print(form.data)
        if form.validate():
            telephone=form.telephone.data
            username=form.username.data
            password=form.password1.data
            user=FrontUser(telephone=telephone,password=password,username=username)
            db.session.add(user)
            db.session.commit()
            return resful.success()
        else:
            print(form.errors)
            return resful.params_error(form.get_error())

@bp.route('/i_forget/',methods=['POST','GET'])
def i_forget():
    if request.method == 'GET':
        return render_template('front/front_iforget.html')
    else:
        form = IForgetForm(request.form)
        if form.validate():
            user = FrontUser.query.filter_by(telephone=form.telephone.data).first()
            print(user)
            user.password = form.password1.data
            db.session.add(user)
            db.session.commit()
            session.clear()
            return resful.success('密码修改成功')
        else:
            print(form.errors)
            return resful.params_error(form.get_error())

bp.add_url_rule('/signup/', view_func=SignUpViews.as_view('signup'))

@bp.route('/add_post/',methods=['POST','GET'])
@login_requried
def add_post():
    if request.method == 'GET':
        boards = BoardModel.query.all()
        cboard=request.args.get('cboard',type=int,default=None)
        return render_template('front/front_add_post.html', boards=boards,cboard=cboard)
    else:

        form = AddPostForm(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
            board_id = form.board_id.data
            board = BoardModel.query.get(board_id)
            if not board:
                return resful.params_error(message='没有这个版块')
            post = PostModel(title=title, content=content, board_id=board_id)
            post.board = board
            post.author = g.front_user
            db.session.add(post)
            db.session.commit()
            return resful.success('注册成功')
        else:
            return resful.params_error(message=form.get_error())


@bp.route('/p/<post_id>')
def post_detail(post_id):
    post=PostModel.query.get(post_id)
    post.reading_count+=1
    db.session.add(post)
    db.session.commit()
    if not post:
        abort(404)
    return render_template('front/front_postdetail.html',post=post)


@bp.route('/add_comment/',methods=['POST'])
@login_requried
def add_comment():
    form=AddCommentForm(request.form)

    if form.validate():
        content=form.content.data
        post_id=form.post_id.data
        post=PostModel.query.get(post_id)
        print(form.data)
        if post:
            comment=CommentModel(content=content)
            comment.post=post
            comment.author=g.front_user
            db.session.add(comment)
            db.session.commit()
            return resful.success()
        else:
            return resful.params_error(message='没有这个帖子')
    else:
        return resful.params_error(form.get_error())

@bp.route('/pwd/')
@login_requried
def pwd():
    return render_template('front/pwd.html')


@bp.route('/search/')
def search():
    q=request.args.get('q')
    posts=PostModel.query.filter(or_(PostModel.title.contains(q),
                                        PostModel.content.contains(q))).order_by(PostModel.create_time.desc()).all()
    boards = BoardModel.query.all()
    return render_template('front/front_search.html',posts=posts,boards=boards)

templates/front/front_add_post.html
{% extends 'front/front_base.html' %}
{% from 'common/macros.html' import static %}

{% block title %}
    发布帖子
{% endblock %}

{% block head %}
    <script src="{{ static('ueditor/ueditor.config.js') }}"></script>
    <script src="{{ static('ueditor/ueditor.all.min.js') }}"></script>
    <script src="{{ static('front/js/front_apost.js') }}"></script>
{% endblock %}

{% block body %}
    <form method="post">
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon">标题</span>
                <input type="text" name="title" class="form-control">
            </div>
        </div>
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon">版块</span>
                <select name="board_id" class="form-control">
                    {% for board in boards %}
                        {% if board.id==cboard %}
                            <option value="{{ board.id }}" selected="selected">{{ board.name }}</option>
                        {% else %}
                            <option value="{{ board.id }}" >{{ board.name }}</option>
                        {% endif %}
                    {% endfor %}

                </select>
            </div>
        </div>

        <div class="form-group">
            <script id="ueditor" type="text/plain" style="height:500px;"></script>
        </div>

        <div class="form-group">
            <button class="btn btn-danger" id="submit-btn">发布帖子</button>
        </div>

    </form>

{% endblock %}

templates/front/front_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% include 'common/_heads.html' %}
    <link rel="stylesheet" href="{{ url_for("static",filename='front/css/front_base.css') }}">
    {% block head %}{% endblock %}
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('front.index') }}" >
                    <img class="logo" src="{{ url_for('static',filename='cms/images/logo.png') }}" ></a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="{{ url_for('front.index') }}">首页 <span class="sr-only">(current)</span></a></li>
                    <li><a href="#">进入论坛</a></li>
                </ul>
                <form class="navbar-form navbar-left" action="{{ url_for('front.search') }}" method="get">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="输入关键字" name="q">
                    </div>
                    <button type="submit" class="btn btn-default">查找</button>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    {% if g.front_user %}
                        <span id="login-tag" data-is-login="1"></span>
                        <li class="dropdown">
                            <a class="dropdown-toggle" id="dropdownMenu1" data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="true">
                                {{ g.front_user.username }}
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                <li><a href="#">个人中心</a></li>
                                <li><a href="#">设置</a></li>
                                <li><a href="{{ url_for('front.log_out') }}">退出登录</a></li>
                            </ul>
                        </li>
                    {% else %}
                        <li><a href="{{ url_for('front.login_in') }}">登录</a></li>
                        <li><a href="{{ url_for('front.signup') }}">注册</a></li>
                    {% endif %}
                 </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
    <div class="main-container">
        {% block body %}{% endblock %}

    </div>
    <br><br>
    <div style="margin:0 auto;text-align: center">
     <div class="footer-box">
        <div class="foot-nav">
            <a href="3" target="_blank">abc360官网</a>
            <span>|</span>
            <a href="#" target="_blank">兰迪官网</a>
            <span>|</span>
            <a href="/help/service" target="_blank">AngleEye</a>
            <span>|</span>
            <a href="/help/goodlink" target="_blank">员工ERP系统</a>
            <span>|</span>
            <a href="/help/goodlink" target="_blank">OA系统</a>
            <!--<span>|</span><a href="/points/gifts" target="_blank">积分商城</a>-->
        </div>
        <div class="foot-nav2">
            <div style="margin-top:6px;">Copyright © 2017 杭州旦悦科技有限公司 All Rights Reserved. </div>
        </div>
         <br>
         <br>
    </div>
    </div>



</body>
</html>

templates/front/front_iforget.html
{% extends 'front/front_signbase.html' %}
{% block title %}
    忘记密码
{% endblock %}
{% block head %}
        <link rel="stylesheet" href="{{ static('front/css/front_signup.css') }}">
    <script src="{{ static('front/js/front_i_forget.js') }}"></script>
{% endblock %}

{% block form_content %}
        <div class="form_signup">

                <div class="form-group">
                    <div class="input-group">
                    <input type="text" class="form-control"  placeholder="输入注册的手机号码" name="telephone">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button" id="sms-captcha-btn">发送验证码</button>
                    </span>
                </div>
                </div>
                <div class="form-group">
                    <input type="text" class="form-control"  placeholder="输入短信验证码" name="sms_captcha">
                </div>
                <div class="form-group">
                    <input type="password" class="form-control"  placeholder="输入新密码" name="password1">
                </div>
                <div class="form-group">
                    <input type="password" class="form-control"  placeholder="请确认密码" name="password2">
                </div>
                <div class="form-group">
                    <div class="input-group">
                        <input type="text" class="form-control"  placeholder="图形验证码" name="graph_captcha">
                        <span class="input-group-addon captcha-addon">
                                <img class="captcha-img" src="{{ url_for('common.graph_captcha') }}" alt=""
                                     id="captcha-img">
                        </span>
                    </div>
                </div>
            <span style="display:none;" id="return-to-span">{{ return_to }}</span>
                <button type="submit" class="btn btn-danger btn-block" id="submit-btn">确认重置密码</button>
                <br>
        </div>
{% endblock %}

templates/front/front_index.html
{% extends 'front/front_base.html' %}
{% block title %}
    兰迪广场
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static',filename= 'front/css/front_index.css') }}">
{% endblock %}

{% block body %}
    <div id="carousel-example-generic" class="carousel slide index-banner" data-ride="carousel">
        <!-- 指示器 -->
        <ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            <li data-target="#carousel-example-generic" data-slide-to="3"></li>
        </ol>

        <!-- 轮播图 -->
        <div class="carousel-inner " role="listbox">
            {% for banner in banners %}
                {% if loop.first %}
                     <div class="item active">
                {% else %}
                    <div class="item">
                {% endif %}
                    <a  href="{{ banner.link_url }}"><img src="{{ banner.image_url }}"
                                 alt="..." style="width: 970px;height: 300px" >
                        <span style="margin-left: 468px">{{ banner.name }}</span>
                    </a>

                    </div>
            {% endfor %}
        </div>


        <!-- 左右切换的控制按钮 -->
        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>


    <div class="post-group">
        <ul class="post-group-head">
              {% if current_sort==1 %}
                    <li class="active"><a href="{{ url_for('front.index',bd=current_board) }}">最新</a></li>
                {% else %}
                    <li><a href="{{ url_for('front.index',bd=current_board) }}">最新</a></li>
                {% endif %}

                {% if current_sort==2 %}
                    <li class="active"><a href="{{ url_for('front.index',st=2,bd=current_board) }}">精华帖子</a></li>
                {% else %}
                    <li><a href="{{ url_for('front.index',st=2,bd=current_board) }}">精华帖子</a></li>
                {% endif %}

                {% if current_sort==3 %}
                    <li class="active"><a href="{{ url_for('front.index',st=3,bd=current_board) }}">阅读最多</a></li>
                {% else %}
                    <li><a href="{{ url_for('front.index',st=3,bd=current_board) }}">阅读最多</a></li>
                {% endif %}

                {% if current_sort==4 %}
                    <li class="active"><a href="{{ url_for('front.index',st=4,bd=current_board) }}">评论最多</a></li>
                {% else %}
                    <li><a href="{{ url_for('front.index',st=4,bd=current_board) }}">评论最多</a></li>
            {% endif %}
        </ul>
        <ul class="post-list-group">
            {% for post in posts %}
            <li>
                <div class="author-avatar-group">
                <img src="{{ post.author.awatar or url_for('static',filename='landi_favicon.ico') }}" alt="">
                </div>
                <div class="post-info-group">
                    <p class="post-title"><a href="{{ url_for('front.post_detail',post_id=post.id) }}">{{ post.title }}</a>
                    {% if post.highlight %}
                        <span class="label label-danger">精华帖</span>
                    {% endif %}
                    </p>
                    <p class="post-info">
                        <span>作者:{{ post.author.username }}</span>
                        <span>发表时间:{{ post.create_time }}</span>
                        <span>评论:{{ post.comments|count }}</span>
                        <span>阅读数 :{{ post.reading_count }}</span>
                    </p>
                </div>
            </li>
            {% endfor %}
        </ul>
        <div style="text-align: center">
            {{ pagination.links }}
        </div>

    </div>

    <div class="sm-container">

        <div class="sm-container">
            <div style="margin-bottom: 10px; margin-top: 20px">
                <a class="btn btn-warning btn-block" href="{{ url_for('front.add_post',cboard=current_board) }}" id="add-post-btn">发布帖子</a>
            </div>


            <div class="list-group">
                {% if current_board %}
                    <a href="/" class="list-group-item">所有板块</a>
                {% else %}
                 <a href="/" class="list-group-item active">所有板块</a>
                {% endif %}
                {% for board in boards %}
                    {% if board.id==current_board %}
                     <a href="{{ url_for('front.index',bd=board.id) }}" class="list-group-item active">{{ board.name }}</a>
                    {% else %}
                    <a href="{{ url_for('front.index',bd=board.id) }}" class="list-group-item">{{ board.name }}</a>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/front/front_login.html
{% extends 'front/front_signbase.html' %}

{% block title %}
    登陆
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{{ static('front/css/front_signup.css') }}">
    <script src="{{ static('front/js/front_signup.js') }}"></script>
    <script src="{{ url_for('static', filename='front/js/front_signin.js') }}"></script>
{% endblock %}

{% block form_content %}
    <div class="form_signup">
        <div class="form-group">
            <input type="text" class="form-control"  placeholder="请输入手机号" name="telephone">
        </div>
        <div class="form-group">
            <input type="password" class="form-control"  placeholder="密码" name="password">
        </div>
        <div class="checkbox">
            <label style="margin-left: -232px " >
                <input type="checkbox" name="remember" value="1"  >记住我
            </label>
        </div>
        <div class="form-group">
            <span style="display:none;" id="return-to-span">{{ return_to }}</span>
            <button class="btn btn-warning btn-block" id="login-submit-btn">立即登录</button>
        </div>
        <div class="form-group">
            <a href="{{ url_for("front.signup") }}" class="signup-link" style="float: left">没有账号？立即注册</a>
            <a href="{{ url_for('front.i_forget') }}" class="resetpwd-link" style="float:right;">找回密码</a>
        </div>
                <br><br>
        </div>
{% endblock %}

templates/front/front_search.html
{% extends 'front/front_base.html' %}
{% block title %}
    兰迪广场
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static',filename= 'front/css/front_index.css') }}">
{% endblock %}

{% block body %}



    <div class="post-group">
        <ul class="post-list-group">
        {% if posts %}
            {% for post in posts %}
            <li>
                <div class="author-avatar-group">
                <img src="{{ post.author.awatar or url_for('static',filename='landi_favicon.ico') }}" alt="">
                </div>
                <div class="post-info-group">
                    <p class="post-title"><a href="{{ url_for('front.post_detail',post_id=post.id) }}">{{ post.title }}</a>
                    {% if post.highlight %}
                        <span class="label label-danger">精华帖</span>
                    {% endif %}
                    </p>
                    <p class="post-info">
                        <span>作者:{{ post.author.username }}</span>
                        <span>发表时间:{{ post.create_time }}</span>
                        <span>评论:{{ post.comments|count }}</span>
                        <span>阅读数 :{{ post.reading_count }}</span>
                    </p>
                </div>
            </li>
            {% endfor %}
        {% else %}
            <p style="font-size: 18px;text-align: center">暂时没有搜到你想要的内容,So Sad......</p>
        {% endif %}
        </ul>
        <div style="text-align: center">

        </div>

    </div>

    <div class="sm-container">

        <div class="sm-container">
            <div style="margin-bottom: 10px; margin-top: 20px">
                <a class="btn btn-warning btn-block" href="{{ url_for('front.add_post',cboard=current_board) }}" id="add-post-btn">发布帖子</a>
            </div>


            <div class="list-group">
                {% if current_board %}
                    <a href="/" class="list-group-item">所有板块</a>
                {% else %}
                 <a href="/" class="list-group-item active">所有板块</a>
                {% endif %}
                {% for board in boards %}
                    {% if board.id==current_board %}
                     <a href="{{ url_for('front.index',bd=board.id) }}" class="list-group-item active">{{ board.name }}</a>
                    {% else %}
                    <a href="{{ url_for('front.index',bd=board.id) }}" class="list-group-item">{{ board.name }}</a>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}