apps/cms/models.py
__author__ = 'yuchen'
__date__ = '2018/8/27 17:38'

from exts import db
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash


# 用户表
class CMSUser(db.Model):
    __tablename__ = 'cms_user'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String(50), nullable=False)
    _password = db.Column(db.String(100), nullable=False)
    email = db.Column(db.String(50), nullable=False, unique=True)
    join_time = db.Column(db.DateTime, default=datetime.now)

    def __init__(self, username, password, email):
        self.username = username
        self.password = password  # 新定义的setter方法被调用了
        self.email = email

    @property
    def password(self):
        return self._password

    @password.setter
    def password(self, raw_password):
        self._password = generate_password_hash(raw_password)

    def check_password(self, raw_password):
        result = check_password_hash(self.password, raw_password)
        # print('结果呢',result)
        return result

    @property
    def permissions(self):
        # 如果该用户没有任何角色，则没有权限
        if not self.roles:
            return 0
        # 遍历该用户拥有的角色，获取该角色权限，并所有所含所有角色权限通过或运算组合在一起
        all_permissions = 0
        for role in self.roles:
            permissions = role.permissions
            all_permissions |= permissions
        return all_permissions

    def has_permission(self, permission):
        # 把传过来的权限和该用户所拥有的权限进行与运算，得出的结果和传过来的权限进行比较，一致的话则拥有该权限
        #  0b00000011 & 0b00000001 ---->1 (0b00000001)
        # all_permissions=self.permissions
        # result = all_permissions & permission == permission
        # return result
        return self.permissions & permission == permission

    @property
    def is_developer(self):
        # 判断该用户是否是开发者，开发者拥有所有权限
        return self.has_permission(CMSPermission.ALL_PERMISSION)


class CMSPermission(object):
    # 255的二进制方式表示11111111
    ALL_PERMISSION = 0b11111111
    # 访问者权限
    VISITOR = 0b00000001
    # 管理帖子权限
    POSTER = 0b00000010
    # 管理评论的权限
    COMMENTER = 0b00000100
    # 管理板块的权限
    BOARDER = 0b00001000
    # 管理前台用户的权限
    FRONTUSER = 0b00010000
    # 管理后台用户的权限
    CMSUSER = 0b00100000
    # 管理所有管理员的权限
    ADMIN = 0b01000000


cms_role_user = db.Table(
    'cms_role_user',
    db.Column('cms_role_id', db.Integer, db.ForeignKey('cms_role.id'), primary_key=True),
    db.Column('cms_user_id', db.Integer, db.ForeignKey('cms_user.id'), primary_key=True)
)


# 角色表
class CMSRole(db.Model):
    __tablename__ = 'cms_role'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String(50), nullable=False)
    desc = db.Column(db.String(200), nullable=True)
    create_time = db.Column(db.DateTime, default=datetime.now)
    permissions = db.Column(db.Integer, default=CMSPermission.VISITOR)
    users = db.relationship('CMSUser', secondary=cms_role_user, backref='roles')

apps/cms/forms.py
__author__ = 'yuchen'
__date__ = '2018/8/27 17:38'

from wtforms import StringField,IntegerField,ValidationError
from wtforms.validators import Email,InputRequired,Length,EqualTo,Regexp
from apps.common.forms import BaseForm
from .models import CMSUser
from utils import landicache
from flask import g
import types



class LoginForm(BaseForm):
    email=StringField(validators=[Email(message='请输入正确格式的邮箱'),InputRequired('请输入邮箱')])
    password=StringField(validators=[Length(6,20,message='请输入正确格式的密码')])
    remember=IntegerField()




class ResetpwdForm(BaseForm):
    oldpwd= StringField(validators=[Length(6,20,message='请输入格式正确的旧密码')])
    newpwd=StringField(validators=[Length(6,20,message='请输入格式正确的新密码')])
    newpwd2=StringField(validators=[EqualTo('newpwd',message='两次输入的密码不一致')])




class RestEmailForm(BaseForm):
    email=StringField(validators=[Email('邮箱格式错误'),InputRequired('请输入邮箱内容')])
    captcha = StringField(validators=[InputRequired('请输入验证码内容'),Length(6,6,message='请输入6位验证码')])

    #自定义验证器保证两次邮箱不一样
    def validate_email(self,field):
        old_email=g.cms_user.email
        print('a',self.email.data)
        print('b',field.data)
        print('g',g.cms_user.email)
        if field.data == old_email:
            raise ValidationError('输入了相同的邮箱')
    #保证缓存的验证码和输入的验证码一致
    def validate_captcha(self,field):
        email=self.email.data
        if email:
            captcha_cache=landicache.get(email)
            if captcha_cache is None or captcha_cache.lower() != field.data.lower():
                raise  ValidationError('验证码不对')
        else:
            raise ValidationError('请输入邮箱')


class AddBannerForm(BaseForm):
    name = StringField(validators=[InputRequired(message='请输入轮播图名称！')])
    image_url = StringField(validators=[InputRequired(message='请输入轮播图图片链接！')])
    link_url = StringField(validators=[InputRequired(message='请输入轮播图跳转链接！')])
    priority = StringField(validators=[InputRequired(message='请输入轮播图优先级！'),Regexp(r'^(0|[1-9][0-9]*)$',
                                                                                  message='优先级请以数字表示')])


class UpdateBannerForm(AddBannerForm):
    banner_id = IntegerField(validators=[InputRequired(message='请输入轮播图的id')])


class AddBoardsForm(BaseForm):
    name=StringField(validators=[InputRequired(message='请输入版块名称'),Length(2,15,message='长度应在2-15个字符之间')])

class UpdateBoardForm(AddBoardsForm):
    board_id=IntegerField(validators=[InputRequired(message='请输入版块名称')])

apps/cms/__init__.py
__author__ = 'yuchen'
__date__ = '2018/8/27 17:37'


from .views import bp
import apps.cms.hooks

apps/cms/views.py
__author__ = 'yuchen'
__date__ = '2018/8/27 17:38'

from flask import Blueprint,render_template,views,request,session,redirect,url_for,g,jsonify
from .forms import LoginForm,ResetpwdForm,RestEmailForm,AddBannerForm,UpdateBannerForm,AddBoardsForm,UpdateBoardForm
from .models import CMSUser,CMSPermission
from sqlalchemy import and_
from datetime import timedelta
from .decorators import login_required,permission_required
from config import CMS_USER_ID
from exts import db,Mail
from utils import resful
from flask_mail import Message
from exts import mail
import string
import random
from utils import landicache
from apps.front.models import BannerModel,BoardModel,HighLight,PostModel,CommentModel,FrontUser
import qiniu
from flask_paginate import Pagination,get_page_parameter




bp=Blueprint('cms',__name__,url_prefix='/cms')


@bp.route('/')
@login_required
def index():
    return render_template('cms/cms_index.html')

@bp.route('/logout/')
@login_required
def logout():
    del session[CMS_USER_ID]
    return redirect(url_for('cms.login'))

@bp.route('/profile/')
@login_required
@permission_required(CMSPermission.VISITOR)
def profile():
    return render_template('cms/cms_profile.html')


@bp.route('/test_email/')
def test_email():
    msg = Message('Flask项目测试邮件',  #这是邮件主题
                  sender='1005862748@qq.com',
                  recipients=['568019867@qq.com'], #发送给谁，这是个列表，可以有多个接收者
                  body='Hello, 这是一封测试邮件，这是邮件的正文')
    mail.send(msg) #发送
    return 'success'

#登陆
class LoginView(views.MethodView):
    def get(self,message=None):
        return render_template('cms/cms_login.html',message=message)
    def post(self):
        form=LoginForm(request.form)
        if form.validate():
            email=form.email.data
            password=form.password.data
            remember=form.remember.data
            user=CMSUser.query.filter(CMSUser.email==email).first()
            if user and user.check_password(password):
                session[CMS_USER_ID]=user.id
                if remember:
                    session.permanent=True
                return redirect(url_for('cms.index'))
            else:
                return self.get(message='邮箱或者密码错误')
        else:
            print(form.errors)
            # message=form.errors.popitem()[1][0]
            message=form.get_error()
            return self.get(message=message)

#修改密码
class ResetPwdView(views.MethodView):
    decorators = [login_required]
    def get(self):
        print(g.cms_user._password,'好')
        return render_template('cms/cms_resetpwd.html')
    def post(self):
        form=ResetpwdForm(request.form)
        print(form.data)
        if form.validate():
            oldpassword=form.oldpwd.data
            newpassword=form.newpwd.data

            user=g.cms_user
            if user.check_password(oldpassword):
                user.password=newpassword
                db.session.commit()
                return resful.success('密码修改成功')
            else:
                return resful.params_error('旧密码输入错误')
        else:
            message=form.get_error()
            return resful.params_error(message)


#修改邮箱
class ResetEmailView(views.MethodView):
    decorators = [login_required]
    def get(self):
        return render_template('cms/cms_resetemail.html')

    def post(self):
        reset_email_form=RestEmailForm(request.form)
        if reset_email_form.validate():
            email=reset_email_form.email.data
            g.cms_user.email=email
            db.session.commit()
            return resful.success('修改成功')
        elif reset_email_form.errors:
            print(reset_email_form.errors)
            errors=reset_email_form.get_error()
            return resful.params_error(errors)
        else:
            return resful.server_error()










bp.add_url_rule('/login/',view_func=LoginView.as_view('login'))
bp.add_url_rule('/resetpwd/',view_func=ResetPwdView.as_view('resetpwd'))
bp.add_url_rule('/resetemail/', view_func=ResetEmailView.as_view('resetemail'))


#发送邮箱验证码
@bp.route('/email_captcha/')
def email_captcha():
    email=request.args.get('email')
    if not email:
        return resful.params_error('请输入你的邮箱')
    source=list(string.ascii_letters)
    source.extend(map(lambda x:str(x),range(0,10)))
    #还有一种写法,但是太low了
    # source.extend(['0','1','2','3','4','5','6','7','8','9','10'])
    random_code_captcha=random.sample(source,6)
    captcha=''.join(random_code_captcha)
    message=Message('论坛邮箱验证码',recipients=[email],body='您的验证码是%s'%captcha)
    try:
        mail.send(message)
    except:
        return resful.server_error()

    landicache.set(email,captcha)

    return resful.success('邮件已发送')


@bp.route('/comments/')
@login_required
@permission_required(CMSPermission.COMMENTER)
def comments():
    comments=CommentModel.query.order_by(CommentModel.create_time.desc()).all()
    return render_template('cms/cms_comments.html',comments=comments)


@bp.route('/fusers/')
@login_required
@permission_required(CMSPermission.FRONTUSER)
def fusers():
    users=FrontUser.query.order_by(FrontUser.join_time.desc()).all()
    return render_template('cms/cms_fusers.html',users=users)

@bp.route('/cusers/')
@login_required
@permission_required(CMSPermission.CMSUSER)
def cusers():
    return render_template('cms/cms_cusers.html')


@bp.route('/croles/')
@login_required
@permission_required(CMSPermission.ALL_PERMISSION)
def croles():
    return render_template('cms/cms_croles.html')
    


@bp.route('/banners/')
@login_required
@permission_required(CMSPermission.COMMENTER)
def banners():
    banners=BannerModel.query.order_by(BannerModel.priority.desc()).all()
    return render_template('cms/cms_banners.html',banners=banners)

@bp.route('/add_banners/',methods=['POST'])
@login_required
def add_banners():
    form=AddBannerForm(request.form)
    if form.validate():
        # name1=request.form.get('name')
        name=form.name.data
        # print(name1,name,'美丽的世界')
        image_url=form.image_url.data
        link_url=form.link_url.data
        priority=form.priority.data
        banner=BannerModel(name=name,image_url=image_url,link_url=link_url,priority=priority)
        db.session.add(banner)
        db.session.commit()
        return resful.success()
    else:
        print(form.errors)
        return resful.params_error(form.get_error())


@bp.route('/update_banners/',methods=['POST','GET'])
@login_required
def update_banners():
    form=UpdateBannerForm(request.form)
    print(form.data,'llal')
    if form.validate():
        banner_id=form.banner_id.data
        name=form.name.data
        image_url=form.image_url.data
        link_url=form.link_url.data
        priority=form.priority.data
        banner=BannerModel.query.get_or_404(banner_id)
        if banner:
            banner.name=name
            banner.image_url=image_url
            banner.link_url=link_url
            banner.priority=priority
            db.session.add(banner)
            db.session.commit()
            return resful.success()
        else:
            return resful.params_error(message='没有这个轮播图')
    else:
        return resful.params_error(message=form.get_error())

@bp.route('/delete_banner/',methods=['POST'])
@login_required
def delete_banner():
    banner_id=request.form.get('banner_id')
    print(banner_id)
    if not banner_id:
        return resful.params_error(message='请传入轮播图id')
    banner=BannerModel.query.get(banner_id)
    if not banner:
        return resful.params_error(message='没有这个轮播图')
    db.session.delete(banner)
    db.session.commit()
    return resful.success()


@bp.route('/uptoken/')
def uptoken():
    access_key='7wL2HnNizlF2OCeFGkmu2KdMG0exOXsA5GQi8EMT'
    secrect_key='fYQ30QziTfynz-osSuoq6pA7xewupEy764l6Zxgl'
    q=qiniu.Auth(access_key,secrect_key)
    bucket='images'
    token=q.upload_token(bucket)
    return jsonify({'uptoken':token})


@bp.route('/boards/')
@login_required
@permission_required(CMSPermission.BOARDER)
def boards():
    board_models=BoardModel.query.all()
    context={
        'boards':board_models
    }
    return render_template('cms/cms_boards.html',**context)

@bp.route('/add_boards/',methods=['POST'])
@login_required
@permission_required(CMSPermission.BOARDER)
def add_boards():
    form=AddBoardsForm(request.form)
    if form.validate():
        name=form.name.data
        board=BoardModel(name=name)
        db.session.add(board)
        db.session.commit()
        return resful.success()
    else:
        return resful.params_error(message=form.get_error())


@bp.route('/update_boards/',methods=['POST'])
@login_required
@permission_required(CMSPermission.BOARDER)
def update_boards():
    form=UpdateBoardForm(request.form)
    if form.validate():
        board_id=form.board_id.data
        name=form.name.data
        board=BoardModel.query.get(board_id)
        if board:
            board.name=name
            db.session.commit()
            return resful.success()
        else:
            return resful.params_error(message='没有这个版块')
    else:
        return resful.params_error(message=form.get_error())


@bp.route('/delete_boards/',methods=['POST'])
@login_required
@permission_required(CMSPermission.BOARDER)
def delete_boards():
    board_id=request.form.get('board_id')
    if not board_id:
        return resful.params_error(message='请传入版块ID')
    board=BoardModel.query.get(board_id)
    if board:
        db.session.delete(board)
        db.session.commit()
        return resful.success()
    else:
        return resful.params_error(message='没有这个版块')

# @bp.route('/delete_post/',methods=['POST'])
# @login_required
# @permission_required(CMSPermission.BOARDER)
# def delete_post():
#     post_id=request.form.get('')

@bp.route('/posts/')
@login_required
@permission_required(CMSPermission.POSTER)
def posts():
    page = request.args.get(get_page_parameter(), type=int, default=1)
    start = (page - 1) * 10
    end = start + 10

templates/cms/cms_banners.html
{% extends 'cms/cms_base.html' %}
{% from 'common/macros.html' import static %}
{% block title %}
    轮播图管理-CMS管理系统
{% endblock %}
{% block head %}
    <script src="https://cdn.staticfile.org/Plupload/2.1.1/moxie.js"></script>
    <script src="https://cdn.staticfile.org/Plupload/2.1.1/plupload.dev.js"></script>
    <script src="https://cdn.staticfile.org/qiniu-js-sdk/1.0.14-beta/qiniu.js"></script>
    <script src="{{ static('common/myqiniu.js') }}"></script>
    <style>

         .top-box button{
            float: right;
        }

    </style>
     <script src="{{ url_for('static', filename='cms/js/banners.js')}}"></script>
{% endblock %}


{% block page_title %}
    轮播图管理
{% endblock %}

{% block main_content %}
    <div class="top-box">
        <button class="btn btn-warning" data-toggle="modal" data-target="#banner-dialog">添加轮播图</button>
    </div>
    <table class="table table-bordered table-hover table-responsive" style="word-break:break-all; word-wrap:break-all;">
            <thead>
                <tr>
                    <th class="col-md-2">名称</th>
                    <th>图片链接</th>
                    <th>跳转链接</th>
                    <th class="col-md-1">优先级</th>
                    <th class="col-md-2">创建时间</th>
                    <th class="col-md-2">操作</th>
                </tr>
            </thead>
            <tbody>
                {% for banner in banners %}
                <tr data-name="{{ banner.name }}" data-image="{{ banner.image_url }}"
                    data-link="{{ banner.link_url }}" data-priority="{{ banner.priority }}"
                    data-id="{{ banner.id }}">
                    <th>{{ banner.name }}</th>
                    <td ><a href="{{ banner.image_url }}" target="_blank">{{ banner.image_url }}</a></td>
                    <td ><a href="{{ banner.link_url }}" target="_blank">{{ banner.link_url }}</a></td>
                    <td>{{ banner.priority }}</td>
                    <td>{{ banner.create_time }}</td>
                    <td>
                        <button class="btn btn-default btn edit-banner-btn">编辑</button>
                        <button class="btn btn-danger btn delete-banner-btn">删除</button>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>


        <!-- Modal -->
        <div class="modal fade" id="banner-dialog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">添加轮播图</h4>
              </div>
              <div class="modal-body">
                    <form class="form-horizontal">
                        <div class="form-group">
                            <label  class="col-sm-2 control-label">名称:</label>
                            <div class="col-sm-9">
                              <input type="text" class="form-control" name="name" placeholder="名称">
                            </div>
                        </div>
                        <div class="form-group">
                            <label  class="col-sm-2 control-label">图片url:</label>
                            <div class="col-sm-7">
                              <input type="text" class="form-control" name="image_url" placeholder="轮播图图片">
                            </div>
                             <button type="button" class="btn btn-info" id="upload-btn">添加图片</button>

                        </div>
                        <div class="form-group">
                            <label  class="col-sm-2 control-label">跳转url:</label>
                            <div class="col-sm-9">
                              <input type="text" class="form-control" name="link_url" placeholder="跳转链接">
                            </div>
                        </div>
                        <div class="form-group">
                            <label  class="col-sm-2 control-label">权重(only数字):</label>
                            <div class="col-sm-9">
                              <input type="text" class="form-control" name="priority" placeholder="优先级">
                            </div>
                        </div>


                    </form>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                <button type="button" class="btn btn-primary" id="save-banner-btn">保存</button>
              </div>
            </div>
          </div>
        </div>

{% endblock %}

templates/cms/cms_base.html
{% from 'common/macros.html' import static %}
 {% set cms_user = g.cms_user %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% include 'common/_heads.html' %}
    <link rel="stylesheet" href="{{ static('cms/css/cms_base.css') }}">
    <script src="{{ static('cms/js/cms_base.js') }}"></script>


    {% block head %}{% endblock %}
</head>
<body>
     <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">兰迪员工BBS管理系统</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{{ url_for('cms.profile') }}">{{ g.cms_user.username }}</a></li>
            <li><a href="{{ url_for('cms.logout') }}">注销</a></li>
          </ul>
          <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="查找...">
          </form>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
          <div class="col-sm-3 col-md-2 sidebar">
              <ul class="nav-sidebar">
                <li class="unfold"><a href="{{ url_for('cms.index') }}">首页</a></li>
                   {% if g.cms_user.has_permission(CMSPermission.VISITOR) %}
                        <li class="profile-li">
                            <a href="#">个人中心<span></span></a>
                            <ul class="subnav">
                                <li><a href="{{ url_for('cms.profile') }}">个人信息</a></li>
                                <li><a href="{{ url_for('cms.resetpwd') }}">修改密码</a></li>
                                <li><a href="{{ url_for('cms.resetemail') }}">修改邮箱</a></li>
                            </ul>
                        </li>
                  {% endif %}
              {% if g.cms_user.has_permission(CMSPermission.POSTER) %}
                  <li class="nav-group banners-manage"><a href="{{ url_for('cms.banners') }}">轮播图管理</a></li>
                  <li class="nav-group post-manage"><a href="{{ url_for('cms.posts') }}">帖子管理</a></li>

              {% endif %}
              {% if g.cms_user.has_permission(CMSPermission.COMMENTER) %}
                  <li class="comments-manage"><a href="{{ url_for('cms.comments') }}">评论管理</a></li>
               {% endif %}
              {% if g.cms_user.has_permission(CMSPermission.BOARDER) %}
                    <li class="board-manage"><a href="{{ url_for('cms.boards') }}">板块管理</a></li>
              {% endif %}

              {% if g.cms_user.has_permission(CMSPermission.FRONTUSER) %}
                <li class="nav-group user-manage"><a href="{{ url_for('cms.fusers') }}">前台用户管理</a></li>
               {% endif %}
                {% if g.cms_user.has_permission(CMSPermission.CMSUSER) %}
                    <li class="nav-group cmsuser-manage"><a href="{{ url_for('cms.cusers') }}">CMS用户管理</a></li>
                {% endif %}
                  {% if g.cms_user.is_developer %}
                      <li class="cmsrole-manage"><a href="{{ url_for('cms.croles') }}">CMS组管理</a></li>
                  {% endif %}
              
            </ul>
          </div>
          <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h1>{% block page_title %}
                {% endblock %}
            </h1>
            <div class="main_content">
                {% block main_content %}
                {% endblock %}
            </div>
          </div>
      </div>
    </div>
</body>
</html>

templates/cms/cms_boards.html
{% extends 'cms/cms_base.html' %}
{%  from'common/macros.html' import static %}
{% block title %}
    板块管理-CMS管理系统
{% endblock %}

{% block head %}
    <script src="{{ static('cms/js/boards.js') }}"></script>
{% endblock %}

{% block page_title %}
    板块管理
{% endblock %}

{% block main_content %}
    <div class="top-box">
        <button class="btn btn-warning" id="add_board_btn" style="float: right">添加新版块</button>
    </div>

    <table class="table table-bordered table-hover table-responsive" style="word-break:break-all; word-wrap:break-all;">
        <thead>
        <tr>
            <th>版块名称</th>
            <th>帖子数量</th>
            <th>创建时间</th>
            <th>操作</th>
        </tr>
        </thead>

        <tbody>
        {% for board in boards %}
            <tr data-name="{{ board.name }}" data-id="{{ board.id }}">
                <td>{{ board.name }}</td>
                <td>0</td>
                <td>{{ board.create_time }}</td>
                <td>
                    <button class="btn btn-default edit-board-btn">编辑</button>
                    <button class="btn btn-danger delete-board-btn">删除</button>
                </td>
            </tr>

        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/cms/cms_comments.html
{% extends 'cms/cms_base.html' %}

{% block title %}
    评论管理-CMS管理系统
{% endblock %}

{% block page_title %}
    评论管理
{% endblock %}

{% block main_content %}
    <table class="table table-bordered" style="word-break:break-all; word-wrap:break-all;">
        <thead>
        <tr>
            <th>评论内容</th>
            <th>评论所属文章</th>
            <th>评论时间</th>
            <th>作者</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for comment in comments %}
            <tr data-id={{ comment.id }} >
                <td><a target="_blank" href="{{ url_for('front.post_detail',post_id=comment.post_id) }}">{{ comment.content }}</a>
                </td>
                <td>{{ comment.post.title }}</td>
                <td>{{ comment.create_time }}</td>
                <td>{{ comment.author.username }}</td>
                <td>
                    <button class="btn btn-danger btn-xs highlight-btn">删除</button>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div style="text-align: center">

    </div>
{% endblock %}

templates/cms/cms_croles.html
{% extends 'cms/cms_base.html' %}

{% block title %}
    CMS组管理-CMS管理系统
{% endblock %}

{% block page_title %}
    CMS组管理
{% endblock %}

{% block main_content %}
    这是CMS组管理页面
{% endblock %}

templates/cms/cms_cusers.html
{% extends 'cms/cms_base.html' %}

{% block title %}
    cms用户管理-CMS管理系统
{% endblock %}

{% block page_title %}
    cms用户管理
{% endblock %}

{% block main_content %}
    这是cms用户管理页面
{% endblock %}

templates/cms/cms_fusers.html
{% extends 'cms/cms_base.html' %}

{% block title %}
    前台用户管理-CMS管理系统
{% endblock %}

{% block page_title %}
    前台用户管理
{% endblock %}

{% block main_content %}
    <table class="table table-bordered" style="word-break:break-all; word-wrap:break-all;">
        <thead>
        <tr>
            <th>用户id</th>
            <th>用户注册电话</th>
            <th>名字</th>
            <th>注册时间</th>

            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr data-id={{ user.id }} >
                <td>{{ user.id}}</td>
                <td>{{ user.telephone}}</td>
                <td>{{ user.username}}</td>
                <td>{{ user.join_time }}</td>
                <td>
                        <button class="btn btn-info btn-xs highlight-btn">禁言</button>

                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div style="text-align: center">

    </div>
{% endblock %}

templates/cms/cms_index.html
{% extends 'cms/cms_base.html' %}

{% block title %}
    网站后台管理页面
{% endblock %}
{% block page_title %}
    欢迎来到这里，后台管理系统还有很多不完善，希望大家多提bug
{% endblock %}